server:
  port: 8082

spring:
  data:
    mongodb:
      host: 192.168.191.140

kafka:
  bootstrap:
    servers: 192.168.191.140:9092
  acks: 1
  buffer:
    memory: 33554432
  retries: 0
  batch:
    size: 1024
  linger:
    ms: 1
  group:
    id: xiaody
  auto:
    commit:
      interval:
        ms: 1000
  session:
    timeout:
      ms: 30000
  enable:
    auto:
      commit: true
